language: node_js
node_js:
  - 12
services:
  - docker
jobs:
  include:
    - stage: build and test
      script:
        - ./setup.sh
        - npm run test
        - ./clean.sh
        - docker build -t philipskinner/elemental:latest .
deploy:
    provider: script
    script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push philipskinner/elemental:latest
    on:
        branch: master