language: node_js
node_js:
  - 12
services:
  - docker
jobs:
  include:
    - stage: build and test
      script:
        - ./setup.sh
        - npm run test
    - stage: docker push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./clean.sh
        - docker pull philipskinner/elemental:master
        - docker build -t philipskinner/elemental:master .
        - docker push philipskinner/elemental:master
      if: branch = master