language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: build and test
      script: 
        - cd ./shared && npm i && cd ..
        - cd ./admin && npm i && cd ..
        - cd ./api && npm i && cd ..
        - cd ./integration && npm i && cd ..
        - cd ./interface && npm i && cd ..
        - cd ./kernel && npm i && cd ..
        - cd ./storage && npm i && cd ..
        - cd ./rules && npm i && cd ..
        - cd ./processes && npm i && cd ..
        - cd ./identity && npm i && cd ..
        - npm i
        - npm run test
